import type { Booking, Car, Customer, Location, Notification } from "@/lib/types"

// Sample cars data
export const carsData: Car[] = [
  {
    id: "car-1",
    make: "Toyota",
    model: "Camry",
    year: 2022,
    price: 50,
    image: "/placeholder.svg?height=200&width=300",
    color: "Silver",
    category: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Gasoline",
    features: ["Bluetooth", "Backup Camera", "Cruise Control"],
    available: true,
    licensePlate: "ABC123",
  },
  {
    id: "car-2",
    make: "Honda",
    model: "CR-V",
    year: 2022,
    price: 65,
    image: "/placeholder.svg?height=200&width=300",
    color: "Blue",
    category: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Gasoline",
    features: ["Navigation", "Sunroof", "Heated Seats"],
    available: true,
    licensePlate: "DEF456",
  },
  {
    id: "car-3",
    make: "Ford",
    model: "Mustang",
    year: 2023,
    price: 85,
    image: "/placeholder.svg?height=200&width=300",
    color: "Red",
    category: "Sports",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Gasoline",
    features: ["Leather Seats", "Premium Sound System", "Performance Package"],
    available: true,
    licensePlate: "GHI789",
  },
  {
    id: "car-4",
    make: "Tesla",
    model: "Model 3",
    year: 2023,
    price: 90,
    image: "/placeholder.svg?height=200&width=300",
    color: "White",
    category: "Electric",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Electric",
    features: ["Autopilot", "Premium Interior", "Long Range Battery"],
    available: true,
    licensePlate: "JKL012",
  },
  {
    id: "car-5",
    make: "Chevrolet",
    model: "Equinox",
    year: 2022,
    price: 60,
    image: "/placeholder.svg?height=200&width=300",
    color: "Black",
    category: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Gasoline",
    features: ["Apple CarPlay", "Android Auto", "Wi-Fi Hotspot"],
    available: true,
    licensePlate: "MNO345",
  },
]

// Sample locations data
export const locationsData: Location[] = [
  {
    id: "location-1",
    name: "Downtown Office",
    address: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    phone: "(212) 555-1234",
    email: "downtown@carrentalservice.com",
    hours: "Mon-Fri: 8am-8pm, Sat-Sun: 9am-5pm",
    coordinates: { lat: 40.7128, lng: -74.006 },
  },
  {
    id: "location-2",
    name: "Airport Terminal",
    address: "456 Airport Rd",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90045",
    phone: "(310) 555-6789",
    email: "airport@carrentalservice.com",
    hours: "Open 24/7",
    coordinates: { lat: 33.9416, lng: -118.4085 },
  },
  {
    id: "location-3",
    name: "Suburban Branch",
    address: "789 Oak Ave",
    city: "Chicago",
    state: "IL",
    zipCode: "60007",
    phone: "(773) 555-4321",
    email: "suburban@carrentalservice.com",
    hours: "Mon-Sat: 9am-7pm, Sun: 10am-4pm",
    coordinates: { lat: 41.8781, lng: -87.6298 },
  },
]

// Sample bookings data
export const bookingsData: Booking[] = [
  {
    id: "booking-1",
    carId: "car-1",
    locationId: "location-1",
    startDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days from now
    endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days from now
    status: "pending",
    totalPrice: 150,
    name: "John Doe",
    email: "john@example.com",
    phone: "(555) 123-4567",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    customerId: "customer-1",
  },
  {
    id: "booking-2",
    carId: "car-2",
    locationId: "location-2",
    startDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days from now
    endDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(), // 14 days from now
    status: "confirmed",
    totalPrice: 455,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "(555) 987-6543",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
    customerId: "customer-2",
  },
  {
    id: "booking-3",
    carId: "car-3",
    locationId: "location-1",
    startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), // 10 days ago
    endDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days ago
    status: "completed",
    totalPrice: 425,
    name: "Robert Johnson",
    email: "robert@example.com",
    phone: "(555) 456-7890",
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(), // 15 days ago
    customerId: "customer-3",
  },
  {
    id: "booking-4",
    carId: "car-4",
    locationId: "location-3",
    startDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
    endDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(), // 4 days from now
    status: "active",
    totalPrice: 630,
    name: "Sarah Williams",
    email: "sarah@example.com",
    phone: "(555) 234-5678",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days ago
    customerId: "customer-4",
  },
  {
    id: "booking-5",
    carId: "car-5",
    locationId: "location-2",
    startDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day from now
    endDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days from now
    status: "cancelled",
    totalPrice: 120,
    name: "Michael Brown",
    email: "michael@example.com",
    phone: "(555) 876-5432",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    customerId: "customer-5",
  },
]

// Sample customers data
export const customersData: Customer[] = [
  {
    id: "customer-1",
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    phone: "(555) 123-4567",
    address: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    driverLicense: "DL12345678",
    bookingHistory: ["booking-1"],
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), // 30 days ago
    name: "John Doe",
    status: "active",
    totalBookings: 1,
    totalSpent: 150,
    bookingIds: ["booking-1"],
    joinedDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    country: "USA",
  },
  {
    id: "customer-2",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane@example.com",
    phone: "(555) 987-6543",
    address: "456 Elm St",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90001",
    driverLicense: "DL87654321",
    bookingHistory: ["booking-2"],
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(), // 45 days ago
    name: "Jane Smith",
    status: "active",
    totalBookings: 1,
    totalSpent: 455,
    bookingIds: ["booking-2"],
    joinedDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    country: "USA",
  },
  {
    id: "customer-3",
    firstName: "Robert",
    lastName: "Johnson",
    email: "robert@example.com",
    phone: "(555) 456-7890",
    address: "789 Oak Ave",
    city: "Chicago",
    state: "IL",
    zipCode: "60007",
    driverLicense: "DL23456789",
    bookingHistory: ["booking-3"],
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(), // 60 days ago
    name: "Robert Johnson",
    status: "active",
    totalBookings: 1,
    totalSpent: 425,
    bookingIds: ["booking-3"],
    joinedDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    country: "USA",
  },
  {
    id: "customer-4",
    firstName: "Sarah",
    lastName: "Williams",
    email: "sarah@example.com",
    phone: "(555) 234-5678",
    address: "321 Pine St",
    city: "Miami",
    state: "FL",
    zipCode: "33101",
    driverLicense: "DL34567890",
    bookingHistory: ["booking-4"],
    createdAt: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString(), // 75 days ago
    name: "Sarah Williams",
    status: "active",
    totalBookings: 1,
    totalSpent: 630,
    bookingIds: ["booking-4"],
    joinedDate: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString(),
    country: "USA",
  },
  {
    id: "customer-5",
    firstName: "Michael",
    lastName: "Brown",
    email: "michael@example.com",
    phone: "(555) 876-5432",
    address: "654 Maple Rd",
    city: "Seattle",
    state: "WA",
    zipCode: "98101",
    driverLicense: "DL45678901",
    bookingHistory: ["booking-5"],
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(), // 90 days ago
    name: "Michael Brown",
    status: "active",
    totalBookings: 1,
    totalSpent: 120,
    bookingIds: ["booking-5"],
    joinedDate: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    country: "USA",
  },
]

// Sample notifications data
export const notificationsData: Notification[] = [
  {
    id: "notif-1",
    type: "new_booking",
    title: "New Booking",
    message: "New booking request received from John Doe",
    timestamp: new Date().toISOString(),
    read: false,
    priority: "high",
    relatedId: "booking-1",
  },
  {
    id: "notif-2",
    type: "booking_update",
    title: "Booking Approved",
    message: "Booking #booking-2 has been approved",
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), // 1 hour ago
    read: true,
    priority: "medium",
    relatedId: "booking-2",
  },
  {
    id: "notif-3",
    type: "booking_update",
    title: "Booking Cancelled",
    message: "Booking #booking-5 has been cancelled",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), // 3 hours ago
    read: false,
    priority: "medium",
    relatedId: "booking-5",
  },
  {
    id: "notif-4",
    type: "system",
    title: "System Update",
    message: "The system will be down for maintenance tonight from 2 AM to 4 AM",
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(), // 12 hours ago
    read: true,
    priority: "low",
    relatedId: "",
  },
  {
    id: "notif-5",
    type: "customer_update",
    title: "New Customer",
    message: "New customer Sarah Williams has been added",
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    read: true,
    priority: "low",
    relatedId: "customer-4",
  },
]
